### PR TITLE
Convert to noarch Python

### PR DESCRIPTION
**Pull request by jakirkham**
Makes the package a `noarch: python` package.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please let me know if you have any thoughts on this. :)

**Comment by danielfrg** [comment]
I think its a great idea! Is there something to review or should we just merge?

**Comment by jakirkham** [comment]
You tell me ;)

**Comment by danielfrg** [comment]
Merging then. Thanks for doing the work!

**Comment by jakirkham** [comment]
Thanks @danielfrg!

**Pull request merged**
