### PR TITLE
Add esc as maintainer

### LINKED ISSUE #11: Can I remove the recipe in bloscpack repo
The Bloscpack repo still carries a conda license:

https://github.com/Blosc/bloscpack/tree/master/conda.recipe

Given the existence of this repo, would it be O.K. to remove that one?

### PR DESCRIPTION
**Pull request by danielfrg**
@esc adding you as maintainer here to fix #11 . Would you like that?

### CODE REVIEW

**Comment by esc** [comment]
Yeah, that would be super sweet, then I can make new conda releases a part of the overall release process! 

On 4 February 2019 17:18:21 CET, Daniel Rodriguez <notifications@github.com> wrote:
>@esc adding you as maintainer here to fix #11 . Would you like that?
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/conda-forge/bloscpack-feedstock/pull/12
>
>-- Commit Summary --
>
>  * Update meta.yaml
>
>-- File Changes --
>
>    M recipe/meta.yaml (1)
>
>-- Patch Links --
>
>https://github.com/conda-forge/bloscpack-feedstock/pull/12.patch
>https://github.com/conda-forge/bloscpack-feedstock/pull/12.diff
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/conda-forge/bloscpack-feedstock/pull/12

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielfrg** [comment]
Perfect!

**Comment by esc** [comment]
@danielfrg thanks again, I may come and bother you with some questions for the next releases if that is O.K.?

**Comment by danielfrg** [comment]
Of course!

**Pull request merged**
